import React, { useState, useEffect, useMemo } from 'react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import { cezaApi } from '../services/api';
import { PAYMENT_URL } from '../services/site';
const money = value => Number(value).toLocaleString('tr-TR', { style: 'currency', currency: 'TRY', maximumFractionDigits: 2 });
export default function CezaListesiPage() {
  const [cezalar, setCezalar] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [q, setQ] = useState(''), [retry, setRetry] = useState(0);
  useEffect(() => { let active = true; setLoading(true); setError(''); cezaApi.getAll().then(d => { if (active) setCezalar(d.cezalar || []); }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [retry]);
  const filtered = useMemo(() => cezalar.filter(c => [c.aciklama, c.kod, c.kanun_maddesi].some(v => (v || '').toLocaleLowerCase('tr-TR').includes(q.trim().toLocaleLowerCase('tr-TR')))).sort((a,b) => b.taban_ceza_tl - a.taban_ceza_tl), [cezalar, q]);
  return <><Helmet><title>2026 Trafik Cezaları Listesi — TrafikRehber</title><meta name="description" content="Trafik cezası türlerini arayın, kayıtlı ceza tutarlarını karşılaştırın ve indirimli ödeme örneğini hesaplayın." /></Helmet><div className="container page-content"><div className="page-intro"><div className="breadcrumb"><Link to="/">Ana Sayfa</Link><span>›</span><span>Ceza Listesi</span></div><h1>2026 trafik cezaları listesi</h1><p>İhlal türünü veya madde kodunu arayın, kayıtlı tutarları karşılaştırın.</p><label htmlFor="fine-search" className="sr-only">İhlal veya madde kodu ara</label><input id="fine-search" type="search" placeholder="İhlal ara: hız, park, telefon…" value={q} onChange={e => setQ(e.target.value)} style={{ width:'100%', maxWidth:650, padding:'13px 16px', border:'1px solid #b9cbd9', borderRadius:9 }} /></div>
    {loading ? <p className="state-message" role="status">Ceza türleri yükleniyor…</p> : error ? <div className="state-message error-state" role="alert"><p>{error}</p><button className="btn btn-secondary" onClick={() => setRetry(r => r + 1)}>Tekrar dene</button></div> : <><p style={{ fontSize:12, marginBottom:14 }} role="status">{filtered.length} ceza türü · Küçük ekranlarda tabloyu yana kaydırabilirsiniz.</p>{filtered.length ? <div className="fine-table-scroll" role="region" aria-label="Ceza tutarları tablosu" tabIndex={0}><table className="fine-table"><caption className="sr-only">Kayıtlı trafik cezası tutarları ve yüzde 25 indirimli ödeme örnekleri</caption><thead><tr><th scope="col">İhlal</th><th scope="col">Kayıtlı tutar</th><th scope="col">%25 indirimli örnek</th><th scope="col">İşlem</th></tr></thead><tbody>{filtered.map(c => <tr key={c.id}><td><strong>{c.aciklama}</strong><small>{c.kanun_maddesi} · {c.kod}</small></td><td>{money(c.taban_ceza_tl)}</td><td>{money(Math.round(Number(c.taban_ceza_tl) * 75) / 100)}</td><td><Link className="btn btn-outline" to={`/araclar/ceza-hesapla?ceza=${encodeURIComponent(c.id)}`} aria-label={`${c.aciklama} için hesapla`}>Hesapla →</Link></td></tr>)}</tbody></table></div> : <p className="state-message">Aramanızla eşleşen ceza bulunamadı.</p>}</>}
    <div className="warning-box">Tablo bilgilendirme amaçlıdır. İhlal tarihi ve koşullara göre tutarlar değişebilir. İndirimli sütun bir hesaplama örneğidir; ödeme öncesinde tutarı ve son ödeme tarihini <a href={PAYMENT_URL} target="_blank" rel="noopener noreferrer">resmi sorgulama hizmetinden</a> doğrulayın.</div><Link to="/dilekce-ornekleri" className="text-link">Dilekçe örneklerini incele →</Link></div></>;
}
