import React, { useState, useEffect } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { cezaApi } from '../services/api';
import { PAYMENT_URL } from '../services/site';
const money = value => Number(value).toLocaleString('tr-TR', { style:'currency', currency:'TRY' });
export default function CezaHesaplaPage() {
  const [params] = useSearchParams();
  const [cezalar, setCezalar] = useState([]), [selected, setSelected] = useState(params.get('ceza') || ''), [result, setResult] = useState(null), [loading, setLoading] = useState(true), [calculating, setCalculating] = useState(false), [error, setError] = useState(''), [retry, setRetry] = useState(0);
  useEffect(() => { let active = true; setLoading(true); setError(''); cezaApi.getAll().then(d => { if (active) setCezalar(d.cezalar || []); }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [retry]);
  async function calculate(e) { e.preventDefault(); setCalculating(true); setResult(null); setError(''); try { setResult(await cezaApi.hesapla(selected)); } catch (err) { setError(err.message); } finally { setCalculating(false); } }
  const valid = cezalar.some(c => c.id === selected);
  return <><Helmet><title>Trafik Cezası Hesaplama — TrafikRehber</title><meta name="description" content="Trafik cezası türünü seçin. Kayıtlı tutarı ve yüzde 25 indirim uygulanması halinde ödeme örneğini karşılaştırın." /></Helmet><div className="container-sm page-content"><div className="page-intro"><div className="breadcrumb"><Link to="/">Ana Sayfa</Link><span>›</span><span>Ceza Hesapla</span></div><h1>Trafik cezası hesapla</h1><p>Ceza türünü seçin, kayıtlı tutarı ve indirimli ödeme örneğini görün.</p></div>{error && <div className="state-message error-state" role="alert"><p>{error}</p>{!cezalar.length && <button className="btn btn-secondary" onClick={() => setRetry(r => r + 1)}>Listeyi yeniden yükle</button>}</div>}<form className="calculator-panel" onSubmit={calculate}><label htmlFor="ceza-type">Ceza türü</label><select id="ceza-type" value={valid ? selected : ''} disabled={loading || calculating} required onChange={e => { setSelected(e.target.value); setResult(null); }}><option value="">{loading ? 'Ceza türleri yükleniyor…' : 'Ceza türü seçin'}</option>{cezalar.map(c => <option key={c.id} value={c.id}>{c.aciklama}</option>)}</select><button type="submit" className="btn btn-primary" disabled={!valid || calculating}>{calculating ? 'Hesaplanıyor…' : 'Ödeme örneğini hesapla'}</button>{!loading && !error && !cezalar.length && <p role="status">Henüz ceza türü eklenmemiş.</p>}</form>{result && <div className="calculation-result" role="status"><h2>{result.ceza.aciklama}</h2><dl className="amount-grid"><div><dt>Kayıtlı ceza tutarı</dt><dd>{money(result.hesaplama.taban_tutar)}</dd></div><div><dt>%25 indirim uygulanırsa</dt><dd>{money(result.hesaplama.erken_odeme_indirimi)}</dd></div></dl><p>Bu hesaplama indirim hakkı veya taksit onayı oluşturmaz. Ödeme tutarını, indirim koşullarını ve son ödeme tarihini tebligatınızdan ya da resmi sorgulama ekranından kontrol edin.</p><p><a href={PAYMENT_URL} target="_blank" rel="noopener noreferrer">e-Devlet’te sorgula ↗</a> · <Link to="/dilekce-ornekleri">Dilekçe örnekleri</Link></p></div>}<p className="warning-box">Tutarlar sitede kayıtlı verilere dayanır. İşleminize özel koşullar için resmi kaynakları esas alın.</p></div></>;
}
